version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:81:81'
      - '127.0.0.1:443:443'
    volumes:
      - nginx-proxy-manager-data:/data
      - letsencrypt-certificates:/etc/letsencrypt
    # networks:
    network_mode: 'bridge'
    environment:
      DISABLE_IPV6: 'true'
# networks:
#   my_bridge_network:
#     driver: bridge

volumes:
  nginx-proxy-manager-data:
  letsencrypt-certificates:
